"""
Django settings for backend_ai project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import json
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-pnjb2%!1j01_sa$s^j1a*m^4cu-)nw02sqfdie5^=(p5t1^kns')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,192.168.1.12,0.0.0.0,10.0.2.2').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'quiz',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # Temporarily disabled
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_ai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# CORS Configuration - Temporarily allow all for testing
# ============================================
CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if os.getenv('CORS_ALLOWED_ORIGINS') else [
#     "http://localhost:3000",      # Web
#     "http://localhost:8081",      # React Native web
#     "http://localhost:19006",     # Expo web preview
#     "http://localhost:19000",     # Expo (alternative)
#     "http://127.0.0.1:3000",
#     "http://127.0.0.1:8081",
#     "http://127.0.0.1:19006",
# ]

CORS_ALLOW_CREDENTIALS = True  # Allow cookies with CORS requests
CORS_EXPOSE_HEADERS = [
    'Content-Type',
    'X-CSRFToken',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'authorization',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# ============================================
# REST Framework Configuration
# ============================================
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',  # Default to AllowAny, secure specific endpoints as needed
    ),
}

# Disable CSRF for API endpoints (DRF handles this via session auth)
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('CSRF_TRUSTED_ORIGINS') else [
    "http://localhost:3000",
    "http://localhost:8081",
    "http://localhost:19006",
    "http://localhost:19000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8081",
    "http://127.0.0.1:19006",
    "http://192.168.1.12:3000",
    "http://192.168.1.12:8081", 
    "http://192.168.1.12:19006",
    "http://192.168.1.12:19000",
]

# ============================================
# Groq API Configuration
# ============================================
GROQ_API_KEY = os.getenv('GROQ_API_KEY')

if not GROQ_API_KEY:
    raise ValueError("GROQ_API_KEY environment variable is not set!")

# ============================================
# API Base URL (untuk frontend)
# ============================================
API_BASE_URL = os.getenv('API_BASE_URL', 'http://localhost:8000/api/')

# ============================================
# Question Distribution (admin configurable)
# Default: 3 questions per difficulty 1..5 (total 15)
# Example override via env: QUESTION_DISTRIBUTION='[{"difficulty":1,"count":2},{"difficulty":2,"count":3}]'
QUESTION_DISTRIBUTION = None
_dist_env = os.getenv('QUESTION_DISTRIBUTION')
if _dist_env:
    try:
        QUESTION_DISTRIBUTION = json.loads(_dist_env)
    except Exception:
        QUESTION_DISTRIBUTION = None

if QUESTION_DISTRIBUTION is None:
    QUESTION_DISTRIBUTION = [
        {"difficulty": 1, "count": 3},
        {"difficulty": 2, "count": 3},
        {"difficulty": 3, "count": 3},
        {"difficulty": 4, "count": 3},
        {"difficulty": 5, "count": 3},
    ]