# Generated by Django 5.2.9 on 2025-12-13 07:56

import django.db.models.deletion
from django.db import migrations, models


def delete_old_topic_data(apps, schema_editor):
    """Clear old topic CharField data - questions will be regenerated via management command"""
    Question = apps.get_model('quiz', 'Question')
    Question.objects.all().delete()
    print("✓ Cleared old question data for clean migration")


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_topic'),
    ]

    operations = [
        migrations.RunPython(delete_old_topic_data, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='QuestionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(default=1)),
                ('target_count', models.IntegerField(default=10)),
                ('current_count', models.IntegerField(default=0)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='quiz.topic')),
            ],
            options={
                'ordering': ['topic', 'difficulty'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.topic'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'difficulty', 'question_type'], name='quiz_questi_topic_i_26b691_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='quiz_questi_is_acti_995386_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionpool',
            unique_together={('topic', 'difficulty')},
        ),
    ]
