# Generated by Django 5.2.9 on 2025-12-13 07:55

import django.db.models.deletion
from django.db import migrations, models


def create_topics_and_map_questions(apps, schema_editor):
    """Create Topic objects from existing question.topic CharField values"""
    Question = apps.get_model('quiz', 'Question')
    Topic = apps.get_model('quiz', 'Topic')
    
    # Get all unique topic values
    unique_topics = Question.objects.filter(
        topic__isnull=False
    ).values_list('topic', flat=True).distinct()
    
    for topic_name in unique_topics:
        topic_str = str(topic_name).strip()[:100]  # Limit to 100 chars
        if topic_str:
            Topic.objects.get_or_create(name=topic_str)
    
    print(f"✓ Created {len(unique_topics)} topics")


def reverse_topics(apps, schema_editor):
    """Rollback - not needed for reverse"""
    pass


def map_topics_to_fk(apps, schema_editor):
    """Map topic names to Topic FK IDs using raw SQL"""
    with schema_editor.connection.cursor() as cursor:
        # For each topic name, find its ID and update questions
        cursor.execute("SELECT DISTINCT topic FROM quiz_question WHERE topic IS NOT NULL")
        topics = cursor.fetchall()
        
        for (topic_name,) in topics:
            topic_str = str(topic_name).strip()[:100]
            if topic_str:
                # Get Topic ID
                cursor.execute("SELECT id FROM quiz_topic WHERE name = %s", [topic_str])
                result = cursor.fetchone()
                if result:
                    topic_id = result[0]
                    cursor.execute(
                        "UPDATE quiz_question SET topic_id = %s WHERE topic = %s",
                        [topic_id, topic_name]
                    )
        
        print(f"✓ Mapped {len(topics)} topics to FK IDs")


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(create_topics_and_map_questions, reverse_topics),
        migrations.CreateModel(
            name='QuestionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(default=1)),
                ('target_count', models.IntegerField(default=10)),
                ('current_count', models.IntegerField(default=0)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='quiz.topic')),
            ],
            options={
                'ordering': ['topic', 'difficulty'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.topic'),
        ),
        migrations.RunPython(map_topics_to_fk, reverse_topics),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'difficulty', 'question_type'], name='quiz_questi_topic_i_26b691_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='quiz_questi_is_acti_995386_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionpool',
            unique_together={('topic', 'difficulty')},
        ),
    ]
