# Generated by Django 5.2.9 on 2025-12-13 07:53

from django.db import migrations


def create_topics_from_questions(apps, schema_editor):
    """Create Topic entries from unique existing question topics"""
    Question = apps.get_model('quiz', 'Question')
    Topic = apps.get_model('quiz', 'Topic')
    
    # Get all unique topic values from existing questions
    unique_topics = Question.objects.filter(
        topic__isnull=False
    ).values_list('topic', flat=True).distinct()
    
    for topic_name in unique_topics:
        if topic_name and topic_name.strip():  # Skip empty values
            Topic.objects.get_or_create(name=topic_name)
    
    print(f"✓ Created {len(unique_topics)} topics from existing questions")


def reverse_populate_topics(apps, schema_editor):
    """Delete all topics (rollback)"""
    Topic = apps.get_model('quiz', 'Topic')
    Topic.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_topic_question_is_active_question_updated_at_and_more'),
    ]

    operations = [
        migrations.RunPython(create_topics_from_questions, reverse_populate_topics),
    ]
