# Generated by Django 5.2.9 on 2025-12-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_usertopicprogress'),
    ]

def seed_topics(apps, schema_editor):
    Topic = apps.get_model('quiz', 'Topic')
    # Define topics with their order
    topics = [
        ("Variabel dan Tipe Data", 1),
        ("Operator", 2),
        ("Percabangan", 3),
        ("Perulangan", 4),
        ("Pengurutan", 5),
        ("Pencarian", 6)
    ]
    for name, order in topics:
        Topic.objects.update_or_create(name=name, defaults={'order': order})

def reverse_seed_topics(apps, schema_editor):
    Topic = apps.get_model('quiz', 'Topic')
    topics = [
        "Variabel dan Tipe Data",
        "Operator",
        "Percabangan",
        "Perulangan",
        "Pengurutan",
        "Pencarian"
    ]
    Topic.objects.filter(name__in=topics).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_usertopicprogress'),
    ]

    operations = [
        migrations.RunPython(seed_topics, reverse_seed_topics),
    ]
