# Generated by Django 5.2.9 on 2025-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_topic_options_topic_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_cases',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
