# Generated by Django 5.2.9 on 2025-12-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_seed_topics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
