# Generated by Django 5.2.9 on 2025-12-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_topic_options_topic_order'),
    ]

def remove_python_basics(apps, schema_editor):
    Topic = apps.get_model('quiz', 'Topic')
    # Delete 'Python Basics' if it exists
    # Use filter().delete() to avoid error if not found
    Topic.objects.filter(name__iexact="Python Basics").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_topic_options_topic_order'),
    ]

    operations = [
        migrations.RunPython(remove_python_basics),
    ]
