# Generated by Django 5.2.9 on 2025-12-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_test_cases'),
        ('quiz', '0008_remove_python_basics'),
    ]

    operations = [
    ]
