# Generated by Django 5.2.9 on 2025-12-20 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_question_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('pretest', 'Pre-test'), ('manual', 'Manual')], default='pretest', max_length=20)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['topic__order', 'unlocked_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='quiz_question_topic_hash_uniq',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='quiz_questi_topic_i_acf323_idx',
            old_name='quiz_question_topic_hash_idx',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('topic', 'question_hash')},
        ),
        migrations.AddField(
            model_name='topicunlock',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='quiz.topic'),
        ),
        migrations.AddField(
            model_name='topicunlock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_unlocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='topicunlock',
            unique_together={('user', 'topic')},
        ),
    ]
