# Generated by Django 5.2.9 on 2025-12-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_question_hash'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='quiz_question_topic_hash_uniq',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='quiz_questi_topic_i_acf323_idx',
            old_name='quiz_question_topic_hash_idx',
        ),
        migrations.AddField(
            model_name='question',
            name='is_pretest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('topic', 'question_hash')},
        ),
    ]
