import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1A233A",
  },
  scrollView: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 30,
    paddingTop: 50,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#ffffff",
    letterSpacing: -0.5,
  },
  rulesButton: {
    backgroundColor: "#3b82f6",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  rulesButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  questionCard: {
    backgroundColor: "#ffffff",
    marginHorizontal: 24,
    padding: 20,
    borderRadius: 12,
    marginBottom: 24,
  },
  codeBlock: {
    backgroundColor: "#f3f4f6",
    padding: 16,
    borderRadius: 8,
    marginBottom: 16,
  },
  codeText: {
    fontFamily: "monospace",
    fontSize: 15,
    color: "#1f2937",
    lineHeight: 22,
    fontWeight: "400",
  },
  questionText: {
    fontSize: 16,
    color: "#374151",
    lineHeight: 24,
    fontWeight: "400",
  },
  optionsContainer: {
    paddingHorizontal: 24,
    gap: 12,
    paddingBottom: 24,
  },
  optionButton: {
    backgroundColor: "#FFFFFF",
    padding: 18,
    borderRadius: 12,
  },
  optionText: {
    fontSize: 16,
    color: "#1f2937",
    fontWeight: "500",
    lineHeight: 22,
  },
  selected: {
    backgroundColor: "#eff6ff",
    borderColor: "#3b82f6",
  },
  selectedText: {
    color: "#3b82f6",
  },
  correct: {
    backgroundColor: "#22c55e",
  },
  wrong: {
    backgroundColor: "#ef4444",
  },
  whiteText: {
    color: "#ffffff",
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "flex-end",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalPositionWrapper: {
    width: "100%",
    paddingBottom: 32,
    position: "relative",
  },
  modalContent: {
    backgroundColor: "#D4E3F7",
    borderRadius: 16,
    padding: 24,
    paddingTop: 20,
  },
  closeLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 12,
  },
  closeIcon: {
    fontSize: 18,
    color: "#ef4444",
    fontWeight: "bold",
  },
  closeText: {
    fontSize: 14,
    color: "#ef4444",
    fontWeight: "600",
  },
  modalEmoji: {
    fontSize: 70,
    position: "absolute",
    right: 0,
    top: -40,
    zIndex: 10,
  },
  modalEmojiImage: {
    width: 70,
    height: 70,
    position: "absolute",
    right: 8,
    top: -36,
    zIndex: 12,
    resizeMode: "contain",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 12,
    lineHeight: 24,
  },
  modalSubtitle: {
    fontSize: 14,
    color: "#374151",
    lineHeight: 22,
    marginBottom: 16,
    textAlign: "justify",
  },
  nextButton: {
    backgroundColor: "transparent",
    borderColor: "#286292",
    borderWidth: 1.5,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  nextButtonText: {
    color: "#286292",
    fontWeight: "600",
    fontSize: 14,
  },
  closeButton: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#f3f4f6",
    justifyContent: "center",
    alignItems: "center",
  },
  closeButtonText: {
    fontSize: 20,
    color: "#666",
    fontWeight: "600",
  },
  nextButtonRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 8,
  },
});
